// @vitest-environment jsdom
import React from 'react';import '@testing-library/jest-dom/vitest';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {cleanup,render,screen,fireEvent,waitFor} from '@testing-library/react';
import DetailCorrectionRequests from './DetailCorrectionRequests';
const {api,state}=vi.hoisted(()=>({api:{corrections:vi.fn(),requestCorrection:vi.fn(),decideCorrection:vi.fn()},state:{actor:7,admin:false,company:12}}));
vi.mock('../AuthContext',()=>({useAuth:()=>({user:{id:state.actor}})}));vi.mock('../CompanyContext',()=>({useCompany:()=>({currentCompany:{id:state.company},platformAdmin:false,companyCapabilities:{canManageCompanyPeople:state.admin}})}));vi.mock('../api',()=>({companyAPI:api}));
beforeEach(()=>{vi.resetAllMocks();state.actor=7;state.admin=false;state.company=12;api.corrections.mockResolvedValue({data:[]});api.requestCorrection.mockResolvedValue({});api.decideCorrection.mockResolvedValue({});});afterEach(cleanup);
it('submits the employee reason to their selected company',async()=>{render(<DetailCorrectionRequests/>);await screen.findByLabelText('Correction reason');fireEvent.change(screen.getByLabelText('Correction reason'),{target:{value:'Correct birth date'}});fireEvent.click(screen.getByRole('button',{name:'Request correction'}));await waitFor(()=>expect(api.requestCorrection).toHaveBeenCalledWith(12,7,{kind:'PROFILE',reason:'Correct birth date'}));});
it('lets a different Company Admin approve once with a decision reason',async()=>{state.actor=5;state.admin=true;api.corrections.mockResolvedValue({data:[{id:9,kind:'PROFILE',reason:'Correct birth date',status:'PENDING',requested_by:7}]});render(<DetailCorrectionRequests userId={7} allowRequest={false}/>);fireEvent.change(await screen.findByLabelText('Decision reason'),{target:{value:'Verified request'}});fireEvent.click(screen.getByRole('button',{name:'Approve one correction'}));await waitFor(()=>expect(api.decideCorrection).toHaveBeenCalledWith(12,7,9,{approve:true,reason:'Verified request'}));});
it('never shows approval controls to the requester or subject',async()=>{state.admin=true;api.corrections.mockResolvedValue({data:[{id:9,kind:'PROFILE',reason:'My correction',status:'PENDING',requested_by:7}]});render(<DetailCorrectionRequests/>);await screen.findByText('My correction');expect(screen.queryByRole('button',{name:'Approve one correction'})).toBeNull();});
