import {useEffect,useState} from 'react';
import {platformAdministrationAPI as api} from '../api';
import {useCompany} from '../CompanyContext';
export default function PlatformCompanyDirectory(){
 const {selectCompany,currentCompany,companies}=useCompany();const [rows,setRows]=useState([]),[query,setQuery]=useState(''),[filter,setFilter]=useState('ALL'),[error,setError]=useState(''),[revision,setRevision]=useState(0),[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;setLoading(true);setError('');api.overview().then(r=>{if(active)setRows(r.data);}).catch(()=>{if(active)setError('Unable to load company overview.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[companies,revision]);
 const expires=r=>r.usage?.endsAt&&Date.parse(r.usage.endsAt)>Date.now()&&Date.parse(r.usage.endsAt)<=Date.now()+30*86400000;
 const shown=rows.filter(r=>(r.name+' '+r.slug+' '+(r.admin_contacts||[]).map(a=>a.email).join(' ')).toLowerCase().includes(query.toLowerCase())).filter(r=>filter==='ALL'||filter==='SUSPENDED'&&r.is_suspended||filter==='EXPIRING'&&expires(r)||filter==='EXPIRED'&&r.usage?.restricted||filter==='ONBOARDING'&&!r.onboarding_complete||filter==='BILLING'&&r.billing_issues>0||filter==='DELIVERY'&&r.delivery_issues>0);
 return <section className="company-card" aria-label="Company directory"><h2>Company directory</h2><div className="platform-form-grid"><label className="company-field">Search companies<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, workspace ID or admin email"/></label><label className="company-field">Company status filter<select value={filter} onChange={e=>setFilter(e.target.value)}>{[['ALL','All companies'],['SUSPENDED','Suspended'],['EXPIRING','Expiring within 30 days'],['EXPIRED','Expired or restricted'],['ONBOARDING','Onboarding incomplete'],['BILLING','Billing issues'],['DELIVERY','Failed admin invitations']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div><button className="button button-secondary" disabled={loading} onClick={()=>setRevision(v=>v+1)}>Refresh overview</button>{error&&<p role="alert">{error}</p>}{loading&&<p role="status">Loading companies…</p>}{!loading&&<><p>{shown.length} companies</p><div className="platform-directory">{shown.map(r=><article className="platform-list-row" key={r.id}><div><h3>{r.name}</h3><p>{r.slug} · {r.is_suspended?'Suspended':'Available'} · {r.onboarding_complete?'Onboarded':'Awaiting admin'}</p><p>{r.usage?.plan?.replaceAll('_',' ')} · {r.usage?.source} · {r.usage?.endsAt?'Ends '+new Date(r.usage.endsAt).toLocaleDateString():'No expiry'}</p><p>{r.usage?.openProjects} / {r.usage?.projects} projects · {r.usage?.activeUsers} / {(r.usage?.includedUsers||0)+(r.usage?.extraSeats||0)} people · {r.usage?.reservations} reserved invitations</p><p>{r.billing_issues} billing issues · {r.delivery_issues} failed admin invitation deliveries</p></div><button className="button button-secondary" disabled={String(currentCompany?.id)===String(r.id)} onClick={()=>selectCompany(r.id).catch(()=>setError('Unable to select company.'))}>View company</button></article>)}</div>{!shown.length&&<p>No companies match these filters.</p>}</>}</section>;
}
