package com.maxwell.chronos.service;
import com.maxwell.chronos.domain.User;
import com.maxwell.chronos.repository.UserRepository;
import jakarta.validation.constraints.*;
import lombok.RequiredArgsConstructor;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;
import org.springframework.http.HttpStatus;
import java.util.*;

@Service @RequiredArgsConstructor @Transactional
public class PlatformAdministrationService {
    private final JdbcTemplate db;
    private final CompanyAccessService access;
    private final UserRepository users;
    private final OnboardingService onboarding;
    private final AuthSessionService sessions;
    public record Plan(@NotBlank @Pattern(regexp="FREE|SINGLE|MULTIPLE|ENTERPRISE|CUSTOM") String tier,@Min(1) @Max(100000) int projectLimit,@Min(1) @Max(100000) int teamLimit,@NotNull @Min(0) Long version,@NotBlank @Size(max=500) String reason) {}
    public record Status(boolean suspended,@NotNull @Min(0) Long version,@NotBlank @Size(max=500) String reason) {}
    public record AccountAction(@NotBlank @Pattern(regexp="LOCK|UNLOCK|DEACTIVATE|REACTIVATE|SIGN_OUT|PROMOTE|DEMOTE|INVITE|REVOKE_INVITATION") String action,@NotNull @Min(0) Long version,@NotBlank @Size(max=500) String reason) {}
    public record AdminInput(@NotBlank @Size(max=100) String firstName,@NotBlank @Size(max=100) String lastName,@NotBlank @Email @Size(max=255) String email) {}
    private long actor(String email){User u=users.findByEmail(email).orElseThrow(()->new AccessDeniedException("Platform Admin permission required"));if(!Boolean.TRUE.equals(access.platformPermissions(u.getId()).capabilities().get("canConfigurePlatform"))||!Boolean.TRUE.equals(db.queryForObject("SELECT EXISTS(SELECT 1 FROM users WHERE id=? AND is_active AND NOT admin_locked AND password_hash IS NOT NULL)",Boolean.class,u.getId())))throw new AccessDeniedException("Platform Admin permission required");return u.getId();}
    private void record(long actor,Long company,Long target,String action,String reason){db.update("INSERT INTO platform_activity(user_id,company_id,target_user_id,action,reason) VALUES (?,?,?,?,?)",actor,company,target,action,reason);}
    public List<Map<String,Object>> companies(String email){actor(email);return db.queryForList("SELECT c.*,EXISTS(SELECT 1 FROM role_assignments r JOIN company_memberships m ON m.company_id=r.company_id AND m.user_id=r.user_id WHERE r.company_id=c.id AND r.project_id IS NULL AND r.role_key='COMPANY_ADMIN' AND r.removed_at IS NULL AND m.status='ACTIVE') onboarding_complete, (SELECT count(*) FROM projects p WHERE p.company_id=c.id AND p.status NOT IN ('COMPLETED','ARCHIVED')) project_count,(SELECT count(*) FROM company_memberships m WHERE m.company_id=c.id AND m.status='ACTIVE') member_count FROM companies c ORDER BY c.name,c.id");}
    public Map<String,Object> company(long id,String email){actor(email);return companies(email).stream().filter(c->((Number)c.get("id")).longValue()==id).findFirst().orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Company not found"));}
    private Map<String,Object> lockedCompany(long id,long version){access.lockCompanyAdministration(id);var row=db.queryForMap("SELECT * FROM companies WHERE id=?",id);if(((Number)row.get("platform_version")).longValue()!=version)throw new ResponseStatusException(HttpStatus.CONFLICT,"Company administration changed. Reload and try again.");return row;}
    public Map<String,Object> usage(long company,String email){actor(email);return db.queryForMap("SELECT (SELECT count(*) FROM projects WHERE company_id=? AND status NOT IN ('COMPLETED','ARCHIVED')) project_count,(SELECT COALESCE(max(n),0) FROM (SELECT p.id,count(DISTINCT pm.user_id)+(SELECT count(DISTINCT i.invitee_email) FROM company_invitations i WHERE i.project_id=p.id AND i.role_key='USER' AND i.accepted_at IS NULL AND i.revoked_at IS NULL AND i.expires_at>now()) n FROM projects p LEFT JOIN project_memberships pm ON pm.project_id=p.id AND pm.status='ACTIVE' WHERE p.company_id=? AND p.status NOT IN ('COMPLETED','ARCHIVED') GROUP BY p.id) teams) largest_team",company,company);}
    public void plan(long company,String email,Plan input){long actor=actor(email);lockedCompany(company,input.version());actor(email);var current=usage(company,email);if(((Number)current.get("project_count")).longValue()>input.projectLimit()||((Number)current.get("largest_team")).longValue()>input.teamLimit())throw new ResponseStatusException(HttpStatus.CONFLICT,"The new limits must cover existing active projects, teams, and pending invitations.");db.update("UPDATE companies SET plan_tier=?,project_limit=?,team_limit=?,platform_version=platform_version+1 WHERE id=?",input.tier(),input.projectLimit(),input.teamLimit(),company);record(actor,company,null,"COMPANY_PLAN_UPDATED",input.reason());}
    public void status(long company,String email,Status input){long actor=actor(email);lockedCompany(company,input.version());actor(email);db.update("UPDATE companies SET is_suspended=?,suspension_reason=?,platform_version=platform_version+1 WHERE id=?",input.suspended(),input.suspended()?input.reason():null,company);record(actor,company,null,input.suspended()?"COMPANY_SUSPENDED":"COMPANY_RESUMED",input.reason());}
    public List<Map<String,Object>> accounts(String email,String query){actor(email);if(query!=null&&query.length()>200)throw new IllegalArgumentException("Search is too long");String search=query==null?"":query.trim();return db.queryForList("SELECT u.id,u.email,u.first_name,u.last_name,u.is_active,u.admin_locked,u.platform_access_version,CASE WHEN u.password_hash IS NULL THEN 'INVITED' ELSE 'ACTIVE' END account_status,EXISTS(SELECT 1 FROM role_assignments r WHERE r.user_id=u.id AND r.role_key='PLATFORM_ADMIN' AND r.removed_at IS NULL AND r.company_id IS NULL) platform_admin,(SELECT count(*) FROM company_memberships m WHERE m.user_id=u.id AND m.status='ACTIVE') active_memberships,(SELECT status FROM invitation_delivery d WHERE d.employee_id=u.id ORDER BY d.id DESC LIMIT 1) delivery_status FROM users u WHERE ?='' OR strpos(lower(u.email||' '||u.first_name||' '||u.last_name),lower(?))>0 ORDER BY u.email LIMIT 100",search,search);}
    private void guardLastAdmin(long target){if(Boolean.TRUE.equals(db.queryForObject("SELECT EXISTS(SELECT 1 FROM role_assignments r JOIN users u ON u.id=r.user_id WHERE r.user_id=? AND r.role_key='PLATFORM_ADMIN' AND r.removed_at IS NULL AND u.is_active AND NOT u.admin_locked AND u.password_hash IS NOT NULL)",Boolean.class,target))&&!Boolean.TRUE.equals(db.queryForObject("SELECT EXISTS(SELECT 1 FROM role_assignments r JOIN users u ON u.id=r.user_id WHERE r.user_id<>? AND r.role_key='PLATFORM_ADMIN' AND r.company_id IS NULL AND r.removed_at IS NULL AND u.is_active AND NOT u.admin_locked AND u.password_hash IS NOT NULL)",Boolean.class,target)))throw new ResponseStatusException(HttpStatus.CONFLICT,"Appoint another available Platform Admin before removing this administrator's access.");}
    public void account(long target,String email,AccountAction input){
        long actor=actor(email);db.queryForObject("SELECT pg_advisory_xact_lock(hashtextextended('chronos-platform-admins',0))",Object.class);access.lockAccountAdministration(target);actor(email);
        var rows=db.queryForList("SELECT id,is_active,admin_locked,password_hash IS NOT NULL activated,platform_access_version FROM users WHERE id=?",target);if(rows.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Account not found");var row=rows.getFirst();if(((Number)row.get("platform_access_version")).longValue()!=input.version())throw new ResponseStatusException(HttpStatus.CONFLICT,"Account changed. Reload and try again.");
        if(target==actor&&Set.of("LOCK","DEACTIVATE","DEMOTE").contains(input.action()))throw new AccessDeniedException("Another Platform Admin must change your administrative access.");
        switch(input.action()){
            case "LOCK","DEACTIVATE","DEMOTE" -> {guardLastAdmin(target);if(!input.action().equals("DEMOTE"))access.guardAccountAdminAccessLoss(target);if(input.action().equals("LOCK"))db.update("UPDATE users SET admin_locked=true,admin_lock_reason=?,locked_at=now(),credential_version=credential_version+1 WHERE id=?",input.reason(),target);else if(input.action().equals("DEACTIVATE"))db.update("UPDATE users SET is_active=false,credential_version=credential_version+1 WHERE id=?",target);else{db.update("UPDATE role_assignments SET removed_at=now() WHERE user_id=? AND role_key='PLATFORM_ADMIN' AND company_id IS NULL AND removed_at IS NULL",target);db.update("UPDATE users SET credential_version=credential_version+1 WHERE id=?",target);}sessions.revokeAll(target);}
            case "UNLOCK" -> db.update("UPDATE users SET admin_locked=false,admin_lock_reason=NULL,locked_until=NULL,failed_login_count=0,unlocked_by=?,unlocked_at=now() WHERE id=?",actor,target);
            case "REACTIVATE" -> db.update("UPDATE users SET is_active=true WHERE id=?",target);
            case "SIGN_OUT" -> {db.update("UPDATE users SET credential_version=credential_version+1 WHERE id=?",target);sessions.revokeAll(target);}
            case "PROMOTE" -> {if(!Boolean.TRUE.equals(row.get("is_active"))||Boolean.TRUE.equals(row.get("admin_locked"))||!Boolean.TRUE.equals(row.get("activated")))throw new IllegalArgumentException("Choose an available activated account");if(Boolean.TRUE.equals(db.queryForObject("SELECT EXISTS(SELECT 1 FROM company_memberships WHERE user_id=? AND status='ACTIVE')",Boolean.class,target)))throw new ResponseStatusException(HttpStatus.CONFLICT,"Remove active company memberships before appointing a Platform Admin.");db.update("INSERT INTO role_assignments(user_id,role_key,assigned_by_user_id) VALUES (?,'PLATFORM_ADMIN',?) ON CONFLICT DO NOTHING",target,actor);db.update("UPDATE users SET credential_version=credential_version+1 WHERE id=?",target);sessions.revokeAll(target);}
            case "INVITE" -> {if(!access.hasPlatformRole(target,"PLATFORM_ADMIN"))throw new AccessDeniedException("Use company invitations to onboard company members");onboarding.invite(target);}
            case "REVOKE_INVITATION" -> {if(!access.hasPlatformRole(target,"PLATFORM_ADMIN")||Boolean.TRUE.equals(row.get("activated")))throw new IllegalArgumentException("Choose an invited Platform Admin");onboarding.revoke(target);db.update("UPDATE role_assignments SET removed_at=now() WHERE user_id=? AND role_key='PLATFORM_ADMIN' AND removed_at IS NULL",target);}
            default -> throw new IllegalArgumentException("Choose a supported account action");
        }
        db.update("UPDATE users SET platform_access_version=platform_access_version+1 WHERE id=?",target);record(actor,null,target,"ACCOUNT_"+input.action(),input.reason());
    }
    public long createAdmin(String email,AdminInput input){long actor=actor(email);db.queryForObject("SELECT pg_advisory_xact_lock(hashtextextended('chronos-platform-admins',0))",Object.class);actor(email);User user=onboarding.create(input.firstName(),input.lastName(),input.email());db.update("INSERT INTO role_assignments(user_id,role_key,assigned_by_user_id) VALUES (?,'PLATFORM_ADMIN',?)",user.getId(),actor);onboarding.invite(user.getId());record(actor,null,user.getId(),"PLATFORM_ADMIN_INVITED",null);return user.getId();}
    public List<Map<String,Object>> audit(String email,int page){actor(email);if(page<0||page>100000)throw new IllegalArgumentException("Invalid page");return db.queryForList("SELECT a.*,u.email actor_email,c.name company_name,t.email target_email FROM platform_activity a LEFT JOIN users u ON u.id=a.user_id LEFT JOIN companies c ON c.id=a.company_id LEFT JOIN users t ON t.id=a.target_user_id ORDER BY a.created_at DESC,a.id DESC LIMIT 100 OFFSET ?",page*100);}
    public List<Map<String,Object>> adminInvitations(long company,String email){actor(email);return db.queryForList("SELECT i.id,i.invitee_email,i.role_key,i.created_at,i.expires_at,i.accepted_at,i.revoked_at,d.status delivery_status,d.attempts,d.sent_at,d.last_error FROM company_invitations i LEFT JOIN LATERAL (SELECT status,attempts,sent_at,last_error FROM invitation_delivery WHERE company_invitation_id=i.id ORDER BY id DESC LIMIT 1) d ON true WHERE i.company_id=? AND i.project_id IS NULL AND i.role_key='COMPANY_ADMIN' AND EXISTS(SELECT 1 FROM platform_activity p WHERE p.company_id=i.company_id AND p.user_id=i.created_by_user_id AND p.action='COMPANY_CREATED') ORDER BY i.id DESC",company);}
}
