ALTER TABLE users ADD COLUMN failed_login_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN last_failed_attempt TIMESTAMP WITH TIME ZONE;
ALTER TABLE users ADD COLUMN locked_until TIMESTAMP WITH TIME ZONE;
ALTER TABLE users ADD COLUMN lockout_cycles INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN admin_locked BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN admin_lock_reason VARCHAR(500);
ALTER TABLE users ADD COLUMN locked_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE users ADD COLUMN unlocked_by BIGINT;
ALTER TABLE users ADD COLUMN unlocked_at TIMESTAMP WITH TIME ZONE;

CREATE TABLE auth_sessions (
  id VARCHAR(36) PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  last_activity_at TIMESTAMP WITH TIME ZONE NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  revoked_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX auth_sessions_user_id_idx ON auth_sessions(user_id);
