ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'ACCOUNT_LOCKED';
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'ACCOUNT_UNLOCKED';
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'SESSIONS_REVOKED';
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'LOGIN_TEMPORARILY_LOCKED';
