ALTER TABLE company_memberships ADD COLUMN membership_version BIGINT NOT NULL DEFAULT 0 CHECK (membership_version >= 0);
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'COMPANY_MEMBERSHIP_REMOVED';
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'COMPANY_MEMBERSHIP_REACTIVATED';
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'COMPANY_ROLE_ASSIGNED';
