const {test,expect}=require('@playwright/test');
async function fixture(page,{platform=false,handler=true,reviewer=true}={}){
 const companies=[{id:12,name:'Company A',slug:'company-a'},{id:13,name:'Company B',slug:'company-b'}],calls=[],writes=[],errors=[];
 let news=[],grants=[],reviews=[],cases=[{id:'case-a',subject:'Private A case',description:'Confidential A details',category:'OTHER_INCIDENT',status:'SUBMITTED',anonymous:true,version:3,submitted_at:'2026-10-01T12:00:00Z',attachments:[],history:[]}];
 page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(({platform})=>{localStorage.setItem('authToken',`test.${btoa(JSON.stringify({exp:Math.floor(Date.now()/1000)+3600}))}.test`);if(!platform&&!localStorage.getItem('chronos:company:5'))localStorage.setItem('chronos:company:5','12');},{platform});
 await page.route('**/api/**',async route=>{
  const req=route.request(),url=new URL(req.url()),path=url.pathname;calls.push(path);let body=[];const company=Number(path.split('/')[3]);
  if(path==='/api/auth/me')body={id:5,email:'admin@example.com',firstName:'Jordan',lastName:'Admin',role:'EMPLOYEE',profileCompleted:true};
  else if(path==='/api/companies/context')body={platformAdmin:platform,memberships:platform?[]:companies,companies,platformPermissions:{roles:platform?['PLATFORM_ADMIN']:[],capabilities:{canCreateCompanies:platform}}};
  else if(/\/companies\/\d+\/context$/.test(path)){const c=companies.find(c=>c.id===company),admin=!platform&&company===12;body={...c,permissions:{companyId:company,companyRoles:admin&&handler?['COMPANY_ADMIN']:[],projects:[],capabilities:admin?{canManageCompanyPeople:true,canManageCompanyAnnouncements:true,canReviewLeaveAndLetters:true,canManageSensitiveGrants:true,canViewCompanyAudit:true,canManagePerformanceReviews:reviewer,canHandleConfidentialReports:handler}:{}}};}
  else if(path.endsWith('/members'))body=[{user_id:5,first_name:'Jordan',last_name:'Admin',email:'admin@example.com',status:'ACTIVE',account_available:true},{user_id:7,first_name:'Case',last_name:'Handler',email:'handler@example.com',status:'ACTIVE',account_available:true},{user_id:8,first_name:'Sam',last_name:'Member',email:'sam@example.com',status:'ACTIVE',account_available:true},{user_id:10,first_name:'Platform',last_name:'Admin',email:'platform@example.com',status:'ACTIVE',account_available:true,platform_account:true}];
  else if(path.endsWith('/employment'))body={companyId:company,userId:5,jobTitle:'Engineer',joiningDate:'2025-01-01'};
  else if(path.includes('/announcements')){
   if(path.endsWith('/announcements')&&req.method()==='GET')body=company===12?news:[];
   else if(path.endsWith('/announcements')&&req.method()==='POST'){const input=req.postDataJSON();writes.push({company,action:'announcement',input});news=[{id:'news-a',company_id:company,title:input.title,content:input.content,publish_date:input.publishDate,priority:input.priority,status:input.status,version:0,acknowledgment_required:input.acknowledgmentRequired}];body='news-a';}
   else if(path.endsWith('/open')){if(company!==12){await route.fulfill({status:404,contentType:'application/json',body:JSON.stringify({message:'Announcement not found'})});return;}body=news[0];}
   else if(path.endsWith('/tracking'))body={total:2,viewed:1,acknowledged:0,employees:[{id:7,name:'Case Handler',email:'handler@example.com'}]};
  }else if(path.endsWith('/sensitive-grants')&&req.method()==='GET')body=grants;
  else if(path.endsWith('/sensitive-grants')&&req.method()==='POST'){const input=req.postDataJSON();writes.push({company,action:'grant',input});grants.push({...input,id:'grant-a',permission:input.permission,user_name:'Case Handler',subject_name:'Sam Member',starts_on:input.startsOn,ends_on:input.endsOn,version:0});body='grant-a';}
  else if(path.includes('/sensitive-grants/')&&req.method()==='DELETE'){writes.push({company,action:'revoke',version:Number(url.searchParams.get('version'))});grants[0].revoked_at='2026-10-05T12:00:00Z';body=null;}
  else if(path.endsWith('/confidential-configuration'))body={companyId:company,handlerConfigured:false};
  else if(path.endsWith('/feedback-reviews/employees'))body=[{id:8,first_name:'Sam',last_name:'Member',email:'sam@example.com',can_review:company===12}];
  else if(path.endsWith('/feedback-reviews/feedback')){
   if(req.method()==='POST'){writes.push({company,action:'feedback',input:req.postDataJSON()});body='feedback-a';}
   else body=company===12?[{id:'feedback-a',content:'Private A recognition',anonymous:true,sender_name:null,sender_type:'Employee',submitted_at:'2026-10-01T12:00:00Z'}]:[];
  }else if(path.includes('/feedback-reviews/reviews')){
   if(path.endsWith('/publish')){writes.push({company,action:'publish',version:Number(url.searchParams.get('version'))});reviews[0].published_at='2026-10-05T12:00:00Z';body=null;}
   else if(req.method()==='POST'){const input=req.postDataJSON();writes.push({company,action:'review',input});reviews=[{...input,id:'review-a',employee_id:input.employeeId,first_name:'Sam',last_name:'Member',employee_name:'Sam Member',employee_email:'sam@example.com',review_year:input.year,can_manage:true,created_at:'2026-10-05T12:00:00Z',modified_at:'2026-10-05T12:00:00Z'}];body='review-a';}
   else body=company===12?reviews:[];
  }else if(path.includes('/employee-reports')){
   if(path.endsWith('/mine'))body=[];
   else if(path.endsWith('/recuse')){writes.push({company,action:'recuse'});cases=[];body=null;}
   else if(req.method()==='PATCH'){const input=req.postDataJSON();writes.push({company,action:'case-review',input});cases[0]={...cases[0],status:input.status,version:4};body=null;}
   else if(req.method()==='POST'){writes.push({company,action:'case-submit'});body={reportId:'receipt-a',status:'SUBMITTED'};}
   else body=path.endsWith('/employee-reports')?cases:cases[0];
  }else if(path.endsWith('/letter-settings')){body={version:0,employers:[{id:'e',name:'Company A',address:'100 Street',email:'hr@example.com'}],signatories:[{id:'h',name:'Casey HR',title:'HR Director'}],templates:[{type:'EMPLOYMENT_VERIFICATION',enabled:true,employerId:'e',signatoryId:'h',body:'Employment details',signatureRequired:false}]};
  }else if(path.endsWith('/letter-settings/availability')){body={companyId:company,templates:[]};
  }else if(path.includes('/letter-requests')){
   const row={id:9,companyId:12,userId:8,userName:'Sam Member',requestedFullName:'Sam Member',requestedJobTitle:'Engineer',employmentStartDate:'2025-01-01',requestType:'EMPLOYMENT_VERIFICATION',status:'SUBMITTED',version:2,submittedAt:'2026-10-01T12:00:00Z',letterPreview:'Company A\nOctober 5, 2026\n\nSubject: Employment letter\n\nEmployment details'};
   if(path.endsWith('/preview')){await route.fulfill({contentType:'application/pdf',body:'%PDF-1.4 preview'});return;}if(path.endsWith('/pending'))body=[row];else if(path.endsWith('/my'))body=[];else if(path.endsWith('/approve')){writes.push({company,action:'letter-approve',input:req.postDataJSON()});body={...row,status:'APPROVED'};}else body=row;
  }else if(path.endsWith('/audit'))body=[{id:'event-a',userName:'Jordan Admin',action:'SENSITIVE_ACCESS_GRANTED',entityType:'SensitiveGrant',entityId:'grant-a',createdAt:'2026-10-05T12:00:00Z'}];
  else if(path.endsWith('/unread-count'))body=0;
  await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(body)});
 });return{calls,writes,errors};
}
test('company admin publishes an announcement and sees only company tracking',async({page})=>{
 const state=await fixture(page);await page.goto('/announcements');await page.getByRole('button',{name:'New announcement'}).click();await page.getByLabel('Title',{exact:true}).fill('A company news');await page.getByLabel('Message',{exact:true}).fill('A only message');await page.getByLabel('Status',{exact:true}).selectOption('PUBLISHED');await page.getByRole('button',{name:'Save announcement'}).click();await expect(page.getByRole('heading',{name:'A company news'})).toBeVisible();await page.getByRole('button',{name:'View tracking'}).click();await expect(page.getByText('handler@example.com',{exact:true})).toBeVisible();expect(state.writes[0]).toMatchObject({company:12,action:'announcement'});
 await page.getByLabel('Current company',{exact:true}).selectOption('13');await expect(page.getByRole('button',{name:'New announcement'})).toHaveCount(0);await expect(page.getByText('A only message',{exact:true})).toHaveCount(0);expect(state.errors).toEqual([]);
});
test('private feedback loads and clears on a company switch',async({page})=>{
 const state=await fixture(page);await page.goto('/feedback');await expect(page.getByText('Private A recognition',{exact:true})).toBeVisible();await page.getByLabel('Current company',{exact:true}).selectOption('13');await expect(page.getByText('Private A recognition',{exact:true})).toHaveCount(0);await expect.poll(()=>state.calls.includes('/api/companies/13/feedback-reviews/feedback')).toBe(true);expect(state.calls).not.toContain('/api/feedback-reviews/feedback');expect(state.errors).toEqual([]);
});
test('company admin grants a subject-specific reviewer and revokes the current version on mobile',async({page})=>{
 const state=await fixture(page);await page.setViewportSize({width:390,height:844});await page.goto('/sensitive-access');await page.getByLabel('Member',{exact:true}).selectOption('7');await page.getByLabel('Permission',{exact:true}).selectOption('PERFORMANCE_REVIEW');await page.getByLabel('Review subject',{exact:true}).selectOption('8');await page.getByLabel('Business purpose',{exact:true}).fill('Quarterly review responsibility');await page.getByRole('button',{name:'Grant access',exact:true}).click();await expect(page.getByText('Access granted.',{exact:true})).toBeVisible();expect(state.writes[0]).toMatchObject({company:12,action:'grant',input:{userId:7,subjectUserId:8,permission:'PERFORMANCE_REVIEW'}});await page.getByRole('button',{name:'Revoke access',exact:true}).click();await expect(page.getByText('Access revoked.',{exact:true})).toBeVisible();expect(state.writes[1]).toEqual({company:12,action:'revoke',version:0});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);expect(state.errors).toEqual([]);
});
test('designated reviewer creates a draft and explicitly publishes the current revision',async({page})=>{
 const state=await fixture(page);await page.goto('/performance-reviews');await page.getByLabel('Search employee by name or email').fill('Sam');await page.getByRole('button',{name:/Sam Member.*sam@example.com/}).click();await page.getByRole('button',{name:'Create quarterly review'}).click();await page.getByLabel('Overall performance summary (required)').fill('Assigned review');await page.getByRole('button',{name:'Save review',exact:true}).click();await page.getByRole('button',{name:'Publish to employee'}).click();await expect(page.getByText('Review published to the employee.',{exact:true})).toBeVisible();expect(state.writes[0]).toMatchObject({company:12,action:'review',input:{employeeId:8,summary:'Assigned review',version:0}});expect(state.writes[1]).toEqual({company:12,action:'publish',version:0});expect(state.errors).toEqual([]);
});
test('confidential handler updates a case with its revision and can recuse',async({page})=>{
 const state=await fixture(page);await page.goto('/confidential-reports');await page.getByRole('button',{name:'Review',exact:true}).click();await expect(page.getByText('Confidential A details',{exact:true})).toBeVisible();await page.getByRole('region',{name:'Report details'}).getByLabel('Status',{exact:true}).selectOption('UNDER_REVIEW');await page.getByLabel('Internal note',{exact:true}).fill('Private handling note');await page.getByRole('button',{name:'Save review',exact:true}).click();await expect.poll(()=>state.writes.length).toBe(1);expect(state.writes[0]).toMatchObject({company:12,action:'case-review',input:{version:3,status:'UNDER_REVIEW',shareWithEmployee:false}});await page.getByRole('button',{name:'Recuse myself from this case'}).click();await expect(page.getByText('No reports match these filters.',{exact:true})).toBeVisible();expect(state.writes[1]).toEqual({company:12,action:'recuse'});expect(state.errors).toEqual([]);
});
test('reporter sees configuration gap and submits anonymously without handler access',async({page})=>{
 const state=await fixture(page,{handler:false,reviewer:false});await page.goto('/workplace-reports');await page.getByRole('button',{name:'Create report',exact:true}).click();await expect(page.getByText(/No eligible Company Admin or confidential handler is available/)).toBeVisible();await page.getByLabel('Report category').selectOption('OTHER_INCIDENT');await page.getByLabel('Report title / subject').fill('A concern');await page.getByLabel('Incident description').fill('Private concern');await page.getByLabel('Report Anonymously').check();await page.getByLabel('I understand what information is retained.').check();await page.getByRole('button',{name:'Submit confidential report'}).click();await expect(page.getByText('receipt-a',{exact:true})).toBeVisible();await page.goto('/confidential-reports');await expect(page).toHaveURL(/\/dashboard$/);expect(state.calls.filter(p=>p==='/api/companies/12/employee-reports')).toHaveLength(1);expect(state.errors).toEqual([]);
});
test('company admin confirms letter details and approves another member with revision',async({page})=>{
 const state=await fixture(page);await page.goto('/letter-management');await page.getByRole('link',{name:'Review letter',exact:true}).click();await page.getByRole('button',{name:'Preview final letter',exact:true}).click();await expect(page.getByTitle('Final letter PDF preview')).toBeVisible();await page.getByLabel('I verified these details for the final PDF').check();await page.getByRole('button',{name:'Approve',exact:true}).click();await expect(page).toHaveURL(/\/letter-management$/);expect(state.writes[0]).toMatchObject({company:12,action:'letter-approve',input:{version:2,fullName:'Sam Member',jobTitle:'Engineer',employmentStartDate:'2025-01-01'}});expect(state.errors).toEqual([]);
});
test('platform context cannot open any company communication or sensitive tool',async({page})=>{
 const state=await fixture(page,{platform:true});for(const path of ['/announcements','/feedback','/performance-reviews','/workplace-reports','/confidential-reports','/requests','/letter-management','/sensitive-access','/audit']){await page.goto(path);await expect(page).toHaveURL(/\/dashboard$/);}expect(state.calls.some(p=>/\/companies\/\d+\/(announcements|feedback-reviews|employee-reports|letter-requests|sensitive-grants|audit)/.test(p))).toBe(false);expect(state.errors).toEqual([]);
});
