import ScreenTitle, {RecordSearch} from '../components/ScreenTitle';
import {LoadingIndicator} from '../components/Hourglass';
import './CompanyManagement.css';
import {useEffect,useState} from 'react';
import {useCompany} from '../CompanyContext';
import {companyGovernanceAPI} from '../api';
export default function AuditLog(){
 const {currentCompany,companyCapabilities}=useCompany();const [rows,setRows]=useState([]),[page,setPage]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{let active=true;setRows([]);setLoading(true);setError('');companyGovernanceAPI(currentCompany.id).audit(page).then(r=>{if(active)setRows(r.data);}).catch(e=>{if(active)setError(e.response?.data?.message||'Unable to load activity.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[currentCompany.id,page,revision]);
 const visible=rows.filter(r=>[r.userName,r.action,r.entityType,r.entityId].join(' ').toLowerCase().includes(search.toLowerCase()));
 return <div className="page-container company-management-page"><div className="header-bar"><ScreenTitle title={companyCapabilities.canViewCompanyAudit?'Company audit':'My activity'} icon="file" eyebrow={companyCapabilities.canViewCompanyAudit?'MANAGEMENT':'WORKSPACE'}/></div><p className="management-help">Activity in {currentCompany.name}. Private feedback, review content, confidential cases, and personal details are excluded.</p>{error&&<p className="error-message" role="alert">{error}</p>}<div className="management-toolbar"><RecordSearch label="Search this page" placeholder="Search this page" value={search} onChange={setSearch}/><button className="button button-secondary" disabled={loading} onClick={()=>setRevision(v=>v+1)}>Reload activity</button></div>{loading?<LoadingIndicator label="Loading activity..."/>:<div className="table-container"><table className="data-table"><thead><tr><th>Date</th><th>Actor</th><th>Action</th><th>Record</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td>{new Date(r.createdAt).toLocaleString()}</td><td>{r.userName||'System'}</td><td>{r.action.replaceAll('_',' ')}</td><td>{r.entityType} {r.entityId}</td></tr>)}</tbody></table>{!visible.length&&<div className="management-empty"><h2>No matching activity.</h2><p>Try another search or reload the activity.</p></div>}</div>}<nav className="management-pagination" aria-label="Activity pages"><button className="button button-secondary" disabled={!page||loading} onClick={()=>setPage(p=>p-1)}>Previous page</button><span> Page {page+1} </span><button className="button button-secondary" disabled={loading||rows.length<100} onClick={()=>setPage(p=>p+1)}>Next page</button></nav></div>;
}
