import {useEffect,useState} from 'react';
import {useCompany} from '../CompanyContext';
import {useAuth} from '../AuthContext';
import {platformAdministrationAPI as api,companyAPI,billingAPI} from '../api';
import './Companies.css';
const failure=e=>e.response?.data?.message||'Unable to complete this action.';
export function PlatformCompanyTools(){
 const {currentCompany,refreshCompanies}=useCompany();const id=currentCompany?.id;
 const [company,setCompany]=useState(null),[usage,setUsage]=useState(null),[invitations,setInvitations]=useState([]),[catalog,setCatalog]=useState(null),[form,setForm]=useState({tier:'CUSTOM',projectLimit:1,teamLimit:7,reason:''}),[adminEmail,setAdminEmail]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{let active=true;if(!id)return;billingAPI.catalog().then(r=>{if(active)setCatalog(r.data);}).catch(()=>{});return()=>{active=false;};},[id]);
 const [billing,setBilling]=useState(null),[retryReason,setRetryReason]=useState('');
 useEffect(()=>{let active=true;setBilling(null);if(!id)return;api.billing(id).then(r=>{if(active)setBilling(r.data);}).catch(()=>{});return()=>{active=false;};},[id,revision]);
 useEffect(()=>{let active=true;setCompany(null);setInvitations([]);setError('');if(!id)return;setBusy(true);Promise.all([api.companies(),api.usage(id),api.adminInvitations(id)]).then(([list,used,invites])=>{if(active){const row=list.data.find(c=>String(c.id)===String(id));setCompany(row);setUsage(used.data);setInvitations(invites.data);if(row)setForm({tier:'CUSTOM',projectLimit:row.project_limit,teamLimit:row.team_limit,reason:''});}}).catch(e=>{if(active)setError(failure(e));}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[id,revision]);
 async function act(callback,message){setBusy(true);setError('');setNotice('');try{await callback();setNotice(message);setRevision(v=>v+1);await refreshCompanies();}catch(e){setError(failure(e));}finally{setBusy(false);}}
 if(!id)return null;
 return <section className="company-card" aria-label="Platform company administration"><h2>Platform company administration</h2><p>Manage availability, plan limits, and Company Admin onboarding for {currentCompany.name}.</p>{error&&<p role="alert">{error} <button onClick={()=>setRevision(v=>v+1)}>Reload company</button></p>}{notice&&<p role="status">{notice}</p>}{busy&&!company&&<p role="status">Loading...</p>}{company&&<>
  <p>Status: <strong>{company.is_suspended?'Suspended':'Available'}</strong></p><p>Open projects: {usage?.project_count||0}. Active company users: {usage?.active_users||0}. Reserved invitations: {usage?.reservations||0}. Capacity: {usage?.user_capacity||0}. Source: {usage?.source||'Free'}.</p>
  {billing&&<div className="company-card"><h3>Billing processing</h3><p>Payment metadata only. These tools do not grant access to employee work or private records.</p>{billing.purchases.map(p=><p key={p.id}>{p.plan_key} · {p.status} · {((p.amount_cents+p.tax_cents)/100).toFixed(2)} USD{p.failure_code?` · ${p.failure_code}`:''}</p>)}<label className="company-field">Reason for retry<input maxLength={500} value={retryReason} onChange={e=>setRetryReason(e.target.value)}/></label>{billing.events.filter(e=>!e.processed_at).map(e=><p key={e.event_id}>{e.event_type} · {e.attempts} attempts · {e.failure_code}<button disabled={busy||!retryReason.trim()} onClick={()=>act(()=>api.retryBilling(id,e.event_id,retryReason),'Verified event retried. Review its processing result.')}>Retry verified event</button></p>)}{!billing.purchases.length&&<p>No company payments recorded.</p>}</div>}
  <form onSubmit={e=>{e.preventDefault();act(()=>api.plan(id,{...form,projectLimit:Number(form.projectLimit),teamLimit:Number(form.teamLimit),version:company.platform_version}),'90-day company grant created. No payment was recorded.');}}><fieldset disabled={busy||usage?.source==='PAID'}><h3>Dated company grant</h3><p>Grants last 90 days and require a reason. Paid terms are purchased and renewed by Company Admins through Billing. A grant never records a payment.</p><label className="company-field">Plan<select aria-label="Plan" value={form.tier} onChange={e=>{const preset=catalog?.plans.find(p=>p.key===e.target.value);setForm({...form,tier:e.target.value,...(preset?{projectLimit:preset.projects,teamLimit:preset.users}:{})});}}>{(catalog?.plans||[]).map(p=><option key={p.key} value={p.key}>{p.name}</option>)}<option value="CUSTOM">Custom allowance</option></select></label><label className="company-field">Open-project limit<input required disabled={form.tier!=='CUSTOM'} type="number" min={1} max={100000} value={form.projectLimit} onChange={e=>setForm({...form,projectLimit:e.target.value})}/></label><label className="company-field">Company user allowance<input required disabled={form.tier!=='CUSTOM'} type="number" min={1} max={100000} value={form.teamLimit} onChange={e=>setForm({...form,teamLimit:e.target.value})}/></label><label className="company-field">Reason for grant<textarea required maxLength={500} value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label><button className="button">Create 90-day grant</button></fieldset></form>
  <form onSubmit={e=>{e.preventDefault();act(()=>api.status(id,{suspended:!company.is_suspended,reason,version:company.platform_version}),company.is_suspended?'Company resumed.':'Company suspended.');}}><fieldset disabled={busy}><h3>Company availability</h3><p>Suspension blocks company operations and invitation acceptance. Accounts, memberships, and history are kept.</p><label className="company-field">Reason for availability change<textarea required maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="button">{company.is_suspended?'Resume company':'Suspend company'}</button></fieldset></form>
  <form onSubmit={e=>{e.preventDefault();act(()=>companyAPI.invite(id,{email:adminEmail,role:'COMPANY_ADMIN'}),'Company Admin invitation queued.');}}><fieldset disabled={busy||company.is_suspended||company.onboarding_complete}><h3>Company Admin onboarding</h3>{company.onboarding_complete&&<p>Initial onboarding is complete. Existing Company Admins manage additional administrator appointments.</p>}<label className="company-field">Company Admin email<input type="email" required maxLength={255} value={adminEmail} onChange={e=>setAdminEmail(e.target.value)}/></label><button className="button">Invite Company Admin</button></fieldset></form>
  <div><h3>Company Admin invitations</h3><p>Invitations and delivery are separate: queued delivery does not mean the email has arrived. Failed delivery can be resent after checking email configuration.</p>{invitations.map(i=><article className="company-card" key={i.id}><strong>{i.invitee_email}</strong><p>Invitation: {i.accepted_at?'Accepted':i.revoked_at?'Revoked':new Date(i.expires_at)<new Date()?'Expired':'Pending'} · Delivery: {i.delivery_status||'Legacy — resend to queue delivery'}</p>{i.last_error&&<p>{i.last_error}</p>}{!i.accepted_at&&!i.revoked_at&&<><button disabled={busy||company.is_suspended||company.onboarding_complete} onClick={()=>act(()=>api.resendAdmin(id,i.id),'Company Admin invitation queued again.')}>Resend invitation</button><button disabled={busy||company.onboarding_complete} onClick={()=>act(()=>api.revokeAdmin(id,i.id),'Company Admin invitation revoked.')}>Revoke invitation</button></>}</article>)}{!invitations.length&&<p>No Company Admin invitations.</p>}</div>
 </>}</section>;
}
export function PlatformAccounts(){
 const {user}=useAuth();const [rows,setRows]=useState([]),[query,setQuery]=useState(''),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[selected,setSelected]=useState(null),[action,setAction]=useState(''),[reason,setReason]=useState(''),[invite,setInvite]=useState({firstName:'',lastName:'',email:''});
 useEffect(()=>{let active=true;setRows([]);setBusy(true);api.accounts(query).then(r=>{if(active)setRows(r.data);}).catch(e=>{if(active)setError(failure(e));}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[query,revision]);
 async function act(callback,message){setBusy(true);setError('');setNotice('');try{await callback();setNotice(message);setSelected(null);setAction('');setReason('');setRevision(v=>v+1);window.dispatchEvent(new Event('chronos:company-memberships-changed'));}catch(e){setError(failure(e));}finally{setBusy(false);}}
 return <div className="page-container companies-page"><h1>Platform accounts</h1><p>Manage shared sign-in access and Platform Admin appointments. Company memberships and roles are managed by Company Admins. Private profiles are not available here.</p>{error&&<p role="alert">{error} <button onClick={()=>setRevision(v=>v+1)}>Reload accounts</button></p>}{notice&&<p role="status">{notice}</p>}
  <form className="company-card" onSubmit={e=>{e.preventDefault();act(async()=>{await api.createAdmin(invite);setInvite({firstName:'',lastName:'',email:''});},'Platform Admin account created and invitation queued.');}}><h2>Invite a Platform Admin</h2><fieldset disabled={busy}><label className="company-field">First name<input required maxLength={100} value={invite.firstName} onChange={e=>setInvite({...invite,firstName:e.target.value})}/></label><label className="company-field">Last name<input required maxLength={100} value={invite.lastName} onChange={e=>setInvite({...invite,lastName:e.target.value})}/></label><label className="company-field">Admin email<input type="email" required maxLength={255} value={invite.email} onChange={e=>setInvite({...invite,email:e.target.value})}/></label><button className="button">Create and invite Platform Admin</button></fieldset></form>
  <label className="company-field">Search accounts<input type="search" maxLength={200} value={query} onChange={e=>setQuery(e.target.value)}/></label>{busy&&!rows.length&&<p role="status">Loading...</p>}{rows.map(r=><article className="company-card" key={r.id}><h2>{r.first_name} {r.last_name}</h2><p>{r.email} · {r.platform_admin?'Platform Admin':'Account'} · {r.is_active?r.admin_locked?'Locked':r.account_status:'Inactive'} · {r.active_memberships} active company memberships</p>{r.delivery_status&&<p>Invitation delivery: {r.delivery_status}</p>}<button disabled={busy} onClick={()=>{setSelected(r);setAction('');setReason('');}}>Manage sign-in access</button></article>)}
  {selected&&<form className="company-card" onSubmit={e=>{e.preventDefault();act(()=>api.account(selected.id,{action,reason,version:selected.platform_access_version}),'Account action completed.');}}><h2>Manage {selected.email}</h2><fieldset disabled={busy}><label className="company-field">Account action<select aria-label="Account action" required value={action} onChange={e=>setAction(e.target.value)}><option value="">Choose an action</option>{[['LOCK','Lock sign-in'],['UNLOCK','Unlock sign-in'],['DEACTIVATE','Deactivate account'],['REACTIVATE','Reactivate account'],['SIGN_OUT','Sign out all sessions'],['PROMOTE','Appoint Platform Admin'],['DEMOTE','Remove Platform Admin'],['INVITE','Resend admin setup invitation'],['REVOKE_INVITATION','Revoke admin setup invitation']].filter(([key])=>!(String(selected.id)===String(user.id)&&['LOCK','DEACTIVATE','DEMOTE'].includes(key))).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><p>Locking or deactivating a shared account affects every company. Platform appointments require an activated account with no active company memberships. An available Platform Admin and each company's last admin must be preserved.</p><label className="company-field">Reason for account action<textarea required maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="button">Confirm account action</button><button type="button" onClick={()=>setSelected(null)}>Cancel</button></fieldset></form>}
 </div>;
}
export function PlatformAudit(){
 const [rows,setRows]=useState([]),[page,setPage]=useState(0),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{let active=true;setRows([]);api.audit(page).then(r=>{if(active)setRows(r.data);}).catch(e=>{if(active)setError(failure(e));});return()=>{active=false;};},[page,revision]);
 return <div className="page-container"><h1>Platform audit</h1><p>Platform provisioning, plan, availability, and account actions. Company operations and private employee content are excluded.</p>{error&&<p role="alert">{error}</p>}<button onClick={()=>setRevision(v=>v+1)}>Reload activity</button>{rows.map(r=><article className="card" key={r.id}><strong>{r.action.replaceAll('_',' ')}</strong><p>{new Date(r.created_at).toLocaleString()} · {r.actor_email} · {r.company_name||r.target_email||'Platform'}</p>{r.reason&&<p>{r.reason}</p>}</article>)}{!rows.length&&!error&&<p>No platform activity on this page.</p>}<button disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous</button><span> Page {page+1} </span><button disabled={rows.length<100} onClick={()=>setPage(p=>p+1)}>Next</button></div>;
}
