package com.maxwell.chronos.service;
import com.maxwell.chronos.dto.*;
import com.maxwell.chronos.enums.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.condition.EnabledIfSystemProperty;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.web.server.ResponseStatusException;
import org.mockito.ArgumentCaptor;
import java.util.*;
import javax.crypto.spec.SecretKeySpec;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import static org.mockito.ArgumentMatchers.*;
@EnabledIfSystemProperty(named="chronos.localDbTest",matches="true")
@SpringBootTest(properties={"spring.datasource.url=jdbc:postgresql://localhost:5432/chronos_dev","spring.datasource.username=chronos_user","spring.datasource.password=chronos_password","chronos.jwtSigningKey=Q2hyb25vcy1kZXZlbG9wbWVudC1rZXktMzItYnl0ZXMtbWluaW11bQ==","chronos.email-alerts.enabled=false","chronos.invitation-delivery.poll-ms=3600000"}) @Transactional
class PlatformCompletionLocalDbTest {
 @Autowired JdbcTemplate db;@Autowired PlatformAdministrationService platform;@Autowired CompanyAccessService access;@Autowired CompanyManagementService companies;@Autowired CompanyWorkflowAccess flows;@Autowired InvitationDeliveryService delivery;
 @MockitoBean InvitationEmailService mail;@MockitoBean NotificationService notifications;
 long p,admin,member,a,b;String platformEmail,adminEmail,memberEmail;
 long user(){String key="platform-test-"+UUID.randomUUID();return db.queryForObject("INSERT INTO users(employee_id,email,first_name,last_name,password_hash,entra_id) VALUES (?,?,'Platform','Test','hash',?) RETURNING id",Long.class,key,key+"@example.com",UUID.randomUUID().toString());}
 String email(long id){return db.queryForObject("SELECT email FROM users WHERE id=?",String.class,id);}
 long company(){return db.queryForObject("INSERT INTO companies(name,slug) VALUES ('Platform Test',?) RETURNING id",Long.class,"platform-test-"+UUID.randomUUID());}
 @BeforeEach void setup(){p=user();admin=user();member=user();platformEmail=email(p);adminEmail=email(admin);memberEmail=email(member);a=company();b=company();db.update("INSERT INTO role_assignments(user_id,role_key) VALUES (?,'PLATFORM_ADMIN')",p);for(long c:new long[]{a,b})for(long u:new long[]{admin,member})db.update("INSERT INTO company_memberships(company_id,user_id,status) VALUES (?,?,'ACTIVE')",c,u);db.update("INSERT INTO role_assignments(user_id,company_id,role_key) VALUES (?,?,'COMPANY_ADMIN')",admin,a);}
 @Test void legacyAdminAndCompanyRolesDoNotAuthorizePlatformActionsOrPrivateProfiles(){db.update("UPDATE users SET role='ADMIN',ssn_last4='1234',date_of_birth='1990-01-01' WHERE id=?",member);assertThrows(AccessDeniedException.class,()->platform.accounts(memberEmail,null));assertThrows(AccessDeniedException.class,()->platform.companies(adminEmail));var account=platform.accounts(platformEmail,memberEmail).getFirst();assertFalse(account.containsKey("ssn_last4"));assertFalse(account.containsKey("date_of_birth"));assertFalse(account.containsKey("password_hash"));assertFalse(account.containsKey("address_line1"));assertEquals(Set.of(p),access.directoryUserIds(p));}
 @Test void suspensionBlocksCompanyWorkAndAcceptanceButKeepsOtherCompanyAndHistory(){companies.invite(a,null,"pending@example.com","PROJECT_ADMIN",admin);platform.status(a,platformEmail,new PlatformAdministrationService.Status(true,0L,"Temporary suspension"));assertTrue(access.companyPermissions(a,admin).capabilities().get("canViewCompanyBilling"));assertFalse(access.companyPermissions(a,admin).capabilities().get("canManageCompanyPeople"));assertFalse(access.hasCompanyRole(a,admin,"COMPANY_ADMIN"));assertThrows(AccessDeniedException.class,()->flows.configuration(a,memberEmail));assertTrue(access.hasActiveCompanyAccess(b,member));assertEquals(2,db.queryForObject("SELECT count(*) FROM company_memberships WHERE company_id=? AND status='ACTIVE'",Integer.class,a));assertTrue(companies.myCompanies(member).stream().noneMatch(c->((Number)c.get("id")).longValue()==a));delivery.deliver();assertEquals("CANCELLED",db.queryForObject("SELECT status FROM invitation_delivery WHERE company_invitation_id IN(SELECT id FROM company_invitations WHERE company_id=?)",String.class,a));verifyNoInteractions(mail);platform.status(a,platformEmail,new PlatformAdministrationService.Status(false,1L,"Available again"));assertTrue(access.hasCompanyRole(a,admin,"COMPANY_ADMIN"));assertEquals(2,db.queryForObject("SELECT count(*) FROM platform_activity WHERE company_id=?",Integer.class,a));}
 @Test void planChangesUseRevisionAndRejectLimitsBelowExistingUsage(){db.update("INSERT INTO projects(company_id,code,name,status,is_active) VALUES (?,'A','A','DRAFT',false),(?,'B','B','DRAFT',false)",a,a);assertEquals(409,assertThrows(ResponseStatusException.class,()->platform.plan(a,platformEmail,new PlatformAdministrationService.Plan("FREE",1,7,0L,"Too small"))).getStatusCode().value());platform.plan(a,platformEmail,new PlatformAdministrationService.Plan("CUSTOM",10,12,0L,"Growth"));assertEquals("CUSTOM",platform.company(a,platformEmail).get("plan_tier"));assertEquals(409,assertThrows(ResponseStatusException.class,()->platform.status(a,platformEmail,new PlatformAdministrationService.Status(true,0L,"Stale"))).getStatusCode().value());assertEquals(1,db.queryForObject("SELECT project_limit FROM companies WHERE id=?",Integer.class,b));}
 @Test void provisioningCommitsCompanyInvitationAndEncryptedJobWhenSmtpIsUnavailable(){doThrow(new IllegalStateException("Private SMTP detail")).when(mail).sendCompanyInvitation(anyString(),anyString(),anyString(),any());String slug="platform-test-"+UUID.randomUUID();long c=companies.createCompany("New company",slug,"initial@example.com",p);assertEquals(1,db.queryForObject("SELECT count(*) FROM company_invitations WHERE company_id=?",Integer.class,c));assertEquals(0,db.queryForObject("SELECT count(*) FROM company_memberships WHERE company_id=?",Integer.class,c));delivery.deliver();var result=platform.adminInvitations(c,platformEmail).getFirst();assertEquals("PENDING",result.get("delivery_status"));assertEquals(1,result.get("attempts"));assertFalse(result.containsKey("token_hash"));assertFalse(result.containsKey("encrypted_token"));assertFalse(result.get("last_error").toString().contains("Private SMTP"));assertTrue(platform.company(c,platformEmail).get("name").equals("New company"));}
 @Test void successfulDeliveryErasesEncryptedTokenAndResendingInvalidatesOldLink(){companies.invite(a,null,"invite@example.com","PROJECT_ADMIN",admin);delivery.deliver();var token=ArgumentCaptor.forClass(String.class);verify(mail).sendCompanyInvitation(eq("invite@example.com"),eq("Platform Test"),token.capture(),any());String old=token.getValue();long invite=db.queryForObject("SELECT id FROM company_invitations WHERE company_id=?",Long.class,a);assertEquals("SENT",db.queryForObject("SELECT status FROM invitation_delivery WHERE company_invitation_id=?",String.class,invite));assertNull(db.queryForObject("SELECT encrypted_token FROM invitation_delivery WHERE company_invitation_id=?",byte[].class,invite));db.update("UPDATE invitation_delivery SET created_at=now()-interval '2 minutes' WHERE company_invitation_id=?",invite);companies.resendInvitation(a,invite,admin);assertThrows(IllegalArgumentException.class,()->companies.previewInvitation(old));assertEquals(2,db.queryForObject("SELECT count(*) FROM invitation_delivery WHERE company_invitation_id=?",Integer.class,invite));assertEquals(1,db.queryForObject("SELECT count(*) FROM company_invitations WHERE company_id=?",Integer.class,a));assertThrows(IllegalArgumentException.class,()->companies.resendInvitation(a,invite,admin));}
 @Test void revocationAndExpiryPreventDeliveryAndPlatformOnlySeesAdminProvisioningInvitations(){companies.invite(a,null,"moderator@example.com","PROJECT_ADMIN",admin);long provisioning=companies.createCompany("Provisioning","platform-test-"+UUID.randomUUID(),"otheradmin@example.com",p);var adminInvites=platform.adminInvitations(provisioning,platformEmail);assertEquals(1,adminInvites.size());long adminInvite=((Number)adminInvites.getFirst().get("id")).longValue();companies.revokePlatformAdminInvitation(provisioning,adminInvite,p);db.update("UPDATE company_invitations SET created_at=now()-interval '2 days',expires_at=now()-interval '1 second' WHERE company_id=? AND role_key='PROJECT_ADMIN'",a);delivery.deliver();assertEquals(2,db.queryForObject("SELECT count(*) FROM invitation_delivery WHERE company_invitation_id IN(SELECT id FROM company_invitations WHERE company_id IN(?,?)) AND status='CANCELLED'",Integer.class,a,provisioning));verifyNoInteractions(mail);assertThrows(AccessDeniedException.class,()->companies.resendInvitation(a,db.queryForObject("SELECT id FROM company_invitations WHERE company_id=? AND role_key='PROJECT_ADMIN'",Long.class,a),p));}
 @Test void encryptedDeliveryWithWrongKeyCannotSendAndFailureDoesNotExposeTokens(){companies.invite(a,null,"encrypted@example.com","PROJECT_ADMIN",admin);new InvitationDeliveryService(db,mail,mock(com.maxwell.chronos.repository.UserRepository.class),new SecretKeySpec(new byte[32],"HmacSHA256")).deliver();verifyNoInteractions(mail);assertEquals(1,db.queryForObject("SELECT attempts FROM invitation_delivery WHERE company_invitation_id IN(SELECT id FROM company_invitations WHERE company_id=?)",Integer.class,a));}
 @Test void platformAdminInvitationUsesScopedRoleAndActivationDeliveryWithoutLegacyPromotion(){String address="new-platform-"+UUID.randomUUID()+"@example.com";long id=platform.createAdmin(platformEmail,new PlatformAdministrationService.AdminInput("New","Admin",address));assertEquals("EMPLOYEE",db.queryForObject("SELECT role::text FROM users WHERE id=?",String.class,id));assertTrue(access.hasPlatformRole(id,"PLATFORM_ADMIN"));assertEquals(0,db.queryForObject("SELECT count(*) FROM company_memberships WHERE user_id=?",Integer.class,id));delivery.deliver();verify(mail).send(argThat(u->u.getId()==id),anyString(),any());}
 @Test void accountActionsRecheckPermissionsRevisionAndLastCompanyAdminAndRevokeSessions(){assertEquals(409,assertThrows(ResponseStatusException.class,()->platform.account(admin,platformEmail,new PlatformAdministrationService.AccountAction("LOCK",0L,"Last company admin"))).getStatusCode().value());platform.account(member,platformEmail,new PlatformAdministrationService.AccountAction("LOCK",0L,"Security review"));assertTrue(db.queryForObject("SELECT admin_locked FROM users WHERE id=?",Boolean.class,member));assertEquals(409,assertThrows(ResponseStatusException.class,()->platform.account(member,platformEmail,new PlatformAdministrationService.AccountAction("UNLOCK",0L,"Stale"))).getStatusCode().value());platform.account(member,platformEmail,new PlatformAdministrationService.AccountAction("UNLOCK",1L,"Resolved"));assertFalse(db.queryForObject("SELECT admin_locked FROM users WHERE id=?",Boolean.class,member));assertThrows(AccessDeniedException.class,()->platform.account(p,platformEmail,new PlatformAdministrationService.AccountAction("DEACTIVATE",0L,"Self")));}
 @Test void platformPromotionRequiresNoActiveCompanyMembershipAndCannotReviveLegacyPrivileges(){assertEquals(409,assertThrows(ResponseStatusException.class,()->platform.account(member,platformEmail,new PlatformAdministrationService.AccountAction("PROMOTE",0L,"Cross scope"))).getStatusCode().value());long id=user();platform.account(id,platformEmail,new PlatformAdministrationService.AccountAction("PROMOTE",0L,"Platform responsibility"));assertTrue(access.hasPlatformRole(id,"PLATFORM_ADMIN"));platform.account(id,platformEmail,new PlatformAdministrationService.AccountAction("DEMOTE",1L,"Responsibility ended"));assertFalse(access.hasPlatformRole(id,"PLATFORM_ADMIN"));assertEquals("EMPLOYEE",db.queryForObject("SELECT role::text FROM users WHERE id=?",String.class,id));}
 @Test void platformAuditContainsOnlyPlatformEventsAndScopedCaAuditNeverReceivesPrivatePlatformNotes(){platform.status(a,platformEmail,new PlatformAdministrationService.Status(true,0L,"Platform availability review"));assertTrue(platform.audit(platformEmail,0).stream().anyMatch(r->r.get("reason")!=null&&r.get("reason").equals("Platform availability review")));platform.status(a,platformEmail,new PlatformAdministrationService.Status(false,1L,"Resume"));assertTrue(flows.audit(a,adminEmail,0).stream().noneMatch(r->r.toString().contains("Platform availability review")));assertThrows(AccessDeniedException.class,()->platform.audit(adminEmail,0));}
 @Test void platformCannotAppointOrManageAdditionalCompanyAdminsOnceOnboardingIsComplete(){assertThrows(AccessDeniedException.class,()->companies.invite(a,null,"backdoor@example.com","COMPANY_ADMIN",p));companies.invite(a,null,"legitimate@example.com","COMPANY_ADMIN",admin);assertTrue(platform.adminInvitations(a,platformEmail).isEmpty());long invitation=db.queryForObject("SELECT id FROM company_invitations WHERE company_id=?",Long.class,a);assertThrows(AccessDeniedException.class,()->companies.resendInvitation(a,invitation,p));assertThrows(AccessDeniedException.class,()->companies.revokePlatformAdminInvitation(a,invitation,p));assertEquals(1,companies.invitations(a,admin).size());}

 @Test void complimentaryPlanHasNoExpiryPaymentAndUsesNormalEntitlements(){
  platform.plan(a,platformEmail,new PlatformAdministrationService.Plan("PRO_PLUS",7,175,0L,"Owned company","COMPLIMENTARY",null));
  var state=new CompanyEntitlements(db).state(a);assertEquals("COMPLIMENTARY",state.source());assertEquals("PRO_PLUS",state.plan());assertEquals(7,state.projects());assertEquals(175,state.includedUsers());assertNull(state.endsAt());
  assertEquals("COMPLIMENTARY",new CompanyEntitlements(db,java.time.Clock.fixed(java.time.Instant.now().plus(java.time.Duration.ofDays(3650)),java.time.ZoneOffset.UTC)).state(a).source());
  assertEquals(0,db.queryForObject("SELECT count(*) FROM company_billing_purchases WHERE company_id=?",Integer.class,a));assertEquals(0,db.queryForObject("SELECT count(*) FROM company_billing_receipts WHERE company_id=?",Integer.class,a));
  assertEquals(1,db.queryForObject("SELECT count(*) FROM platform_activity WHERE company_id=? AND action='COMPANY_COMPLIMENTARY_PLAN_ASSIGNED' AND reason='Owned company'",Integer.class,a));
  assertEquals(1,db.queryForObject("SELECT revision FROM company_billing_profiles WHERE company_id=?",Integer.class,a));
 }
 @Test void complimentaryExpiryReturnsToFreeAndRevocationRetainsHistory(){
  var end=java.time.Instant.now().plusSeconds(3600);platform.plan(a,platformEmail,new PlatformAdministrationService.Plan("PRO",3,75,0L,"Temporary allowance","COMPLIMENTARY",end));
  assertEquals(end.toEpochMilli(),new CompanyEntitlements(db).state(a).endsAt().toEpochMilli());
  var expired=new CompanyEntitlements(db,java.time.Clock.fixed(end.plusSeconds(1),java.time.ZoneOffset.UTC)).state(a);assertEquals("FREE",expired.source());assertEquals(1,expired.projects());assertEquals(7,expired.includedUsers());
  platform.revokeGrant(a,platformEmail,new PlatformAdministrationService.GrantRevocation(1L,"Allowance ended"));assertEquals("FREE",new CompanyEntitlements(db).state(a).source());
  assertEquals(2,db.queryForObject("SELECT count(*) FROM company_memberships WHERE company_id=?",Integer.class,a));assertEquals("SUPERSEDED",db.queryForObject("SELECT status FROM company_billing_terms WHERE company_id=?",String.class,a));
  assertEquals(1,db.queryForObject("SELECT count(*) FROM platform_activity WHERE company_id=? AND action='COMPANY_COMPLIMENTARY_PLAN_REVOKED'",Integer.class,a));
 }
 @Test void complimentaryChangesRequirePlatformPermissionCurrentRevisionAndCatalogLimits(){
  assertThrows(AccessDeniedException.class,()->platform.plan(a,adminEmail,new PlatformAdministrationService.Plan("PRO",3,75,0L,"Forged","COMPLIMENTARY",null)));
  assertThrows(IllegalArgumentException.class,()->platform.plan(a,platformEmail,new PlatformAdministrationService.Plan("PRO",30,750,0L,"Wrong limits","COMPLIMENTARY",null)));
  assertThrows(IllegalArgumentException.class,()->platform.plan(a,platformEmail,new PlatformAdministrationService.Plan("PRO",3,75,0L,"Expired","COMPLIMENTARY",java.time.Instant.now().minusSeconds(1))));
  platform.plan(a,platformEmail,new PlatformAdministrationService.Plan("PRO",3,75,0L,"Owned company","COMPLIMENTARY",null));
  assertThrows(ResponseStatusException.class,()->platform.revokeGrant(a,platformEmail,new PlatformAdministrationService.GrantRevocation(0L,"Stale")));
  assertThrows(AccessDeniedException.class,()->platform.revokeGrant(a,adminEmail,new PlatformAdministrationService.GrantRevocation(1L,"Forged")));
 }
 @Test void complimentaryDowngradeAndRevocationCountAdminOnlyPeopleAndInvitations(){
  for(int i=0;i<6;i++){long u=user();db.update("INSERT INTO company_memberships(company_id,user_id,status,workforce_enabled) VALUES (?,?,'ACTIVE',FALSE)",a,u);}
  platform.plan(a,platformEmail,new PlatformAdministrationService.Plan("PRO",3,75,0L,"Owned company","COMPLIMENTARY",null));
  assertThrows(ResponseStatusException.class,()->platform.plan(a,platformEmail,new PlatformAdministrationService.Plan("FREE",1,7,1L,"Too many people","COMPLIMENTARY",null)));
  assertThrows(ResponseStatusException.class,()->platform.revokeGrant(a,platformEmail,new PlatformAdministrationService.GrantRevocation(1L,"Too many people")));
  db.update("UPDATE company_memberships SET status='REMOVED' WHERE company_id=? AND workforce_enabled=FALSE",a);
  for(int i=0;i<6;i++)companies.invite(a,null,"admin-reservation-"+i+"-"+UUID.randomUUID()+"@example.com","COMPANY_ADMIN",admin);
  assertThrows(ResponseStatusException.class,()->platform.revokeGrant(a,platformEmail,new PlatformAdministrationService.GrantRevocation(1L,"Reserved people")));
 }
 @Test void complimentaryGrantCannotReplaceActiveOrScheduledPaidTerms(){
  db.update("INSERT INTO company_billing_terms(id,company_id,plan_key,source,starts_at,ends_at,project_limit,included_users,catalog_version) VALUES (?,?,'PRO','PAID',now()+interval '1 day',now()+interval '90 days',3,75,'test')",UUID.randomUUID(),a);
  assertThrows(ResponseStatusException.class,()->platform.plan(a,platformEmail,new PlatformAdministrationService.Plan("PRO_PLUS",7,175,0L,"Owned company","COMPLIMENTARY",null)));
 }

 @Test void complimentaryPlanDoesNotLiftAdministrativeSuspension(){
  platform.status(a,platformEmail,new PlatformAdministrationService.Status(true,0L,"Paused"));
  platform.plan(a,platformEmail,new PlatformAdministrationService.Plan("PRO_PLUS",7,175,1L,"Owned company","COMPLIMENTARY",null));
  assertTrue(db.queryForObject("SELECT is_suspended FROM companies WHERE id=?",Boolean.class,a));assertFalse(access.hasCompanyRole(a,admin,"COMPANY_ADMIN"));assertEquals("COMPLIMENTARY",new CompanyEntitlements(db).state(a).source());
 }
}
